### ISSUE TITLE
[BUG] Unexpected token with code

### ISSUE THREAD

**Issue by leonj1** [nirelbaz/meniai#2]
**Describe the bug**
Invoking the command without any arguments leads to this error:
$ meniai
/home/gitpod/.nvm/versions/node/v20.17.0/bin/meniai: line 1: syntax error near unexpected token `('
/home/gitpod/.nvm/versions/node/v20.17.0/bin/meniai: line 1: `var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {'

**To Reproduce**
Followed installation instructions in the readme.
Second step in readme was to run: meniai

**Expected behavior**
The readme states there should be a wizard with steps that I should follow, but that never appears.

**Environment (please complete the following information):**

- OS: Linux Ubuntu 22.04
- MeniAI version: unknown since the above error always appears.

**Comment by nirelbaz** [comment]
Hey @leonj1! Thank you for opening an issue. The issue was that the executable file was missing the [shebang line](https://en.wikipedia.org/wiki/Shebang_(Unix)). I've added it in version 1.0.4 (https://github.com/nirelbaz/meniai/commit/de5e0a5d6f12d77349dd20d2137b21bff5028821).

Please let me know if it works for you now. Thanks again and I hope that MeniAi will prove useful for you :)

**Comment by nirelbaz** [comment]
Great! Thanks again 🙏🏻
